name: "PM2 Deployment"
description: "Deploy your nodejs or typescript app with PM2"

on:
  workflow_call:
    secrets:
      host:
        description: "Remote host"
        required: true
      username:
        description: "Username to login"
        required: true
      port:
        description: "SSH port"
        required: false
        default: "22"
      password:
        description: "SSH password"
        required: false
      key:
        description: "SSH key"
        required: false

    inputs:
      build:
        required: false
        default: "false"
      port:
        description: "SSH port"
        required: false
        default: "22"
      remote-path:
        description: "Remote path where the files are going to be copied"
        required: true
      pm2-id:
        description: "PM2 ID or Name of the process"
        required: true

jobs:
  build-and-deploy:
    if: secrets.password || inputs.key
    runs-on: ubuntu-latest
    steps:
      - name: Get repository content
        uses: actions/checkout@v4

      - name: Copy repository content
        uses: appleboy/scp-action@v0.1.7
        env:
          HOST: ${{ secrets.host }}
          USERNAME: ${{ secrets.username }}
          PORT: ${{ inputs.port || secrets.port }}
          PASSWORD: ${{ secrets.password }}
          KEY: ${{ inputs.key }}
        with:
          source: "."
          target: ${{ inputs.remote-path }}

      - name: Install project
        uses: appleboy/ssh-action@v1.0.3
        with:
          HOST: ${{ secrets.host }}
          USERNAME: ${{ secrets.username }}
          PORT: ${{ inputs.port || secrets.port }}
          PASSWORD: ${{ secrets.password }}
          KEY: ${{ inputs.key }}
          script: cd ${{ inputs.remote-path }} && npm ci

      - name: Build your project
        if: ${{ inputs.build == true }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          HOST: ${{ secrets.host }}
          USERNAME: ${{ secrets.username }}
          PORT: ${{ inputs.port || secrets.port }}
          PASSWORD: ${{ secrets.password }}
          KEY: ${{ inputs.key }}
          script: cd ${{ inputs.remote-path }} && npm run build

      - name: Reload remote application
        uses: appleboy/ssh-action@v1.0.3
        with:
          HOST: ${{ secrets.host }}
          USERNAME: ${{ secrets.username }}
          PORT: ${{ inputs.port || secrets.port }}
          PASSWORD: ${{ secrets.password }}
          KEY: ${{ inputs.key }}
          script: cd ${{ inputs.remote-path }} && pm2 reload ecosystem.config.js

      - name: Reset number of restarts
        uses: appleboy/ssh-action@v1.0.3
        with:
          HOST: ${{ secrets.host }}
          USERNAME: ${{ secrets.username }}
          PORT: ${{ inputs.port || secrets.port }}
          PASSWORD: ${{ secrets.password }}
          KEY: ${{ inputs.key }}
          script: pm2 reset ${{ inputs.pm2-id }}
